Pull Request for Code Review
anemoneflower/MSQ_SegQ pull request #2
Opened 2020-04-18 08:53 UTC by anemoneflower

2020-04-18 10:24 UTC, jeehoonkang requested changes
더 리뷰를 하기 전에 cargo fmt, cargo clippy 먼저 한번씩 돌려주시길 부탁드려요.

2020-04-18 10:24 UTC, jeehoonkang commented on src/msqueue.rs
> +//maqueue => skeleton from cs492-concur-master/lockfree/queue
여기에는 `//!` 로 주석을 달아야 합니다.

2020-04-18 17:57 UTC, anemoneflower commented on src/msqueue.rs
> +//maqueue => skeleton from cs492-concur-master/lockfree/queue
감사합니다.
피드백 수정하여 커밋 올렸습니다.

2020-04-18 18:03 UTC, jeehoonkang requested changes
- 테스트는 잘 되나요?
- 알고리즘은 이해했는지 궁금합니다.
- PR 이름은 좀더 의미가 있어야 합니다.  가령 "Add MSqueue" 정도로..
- segment queue는 아직 안한거죠?

2020-04-18 18:03 UTC, jeehoonkang commented on src/msqueue.rs
> +//! maqueue => skeleton from cs492-concur-master/lockfree/queue
"msqueue"?

2020-04-18 18:03 UTC, jeehoonkang commented on src/msqueue.rs
> +            data: unsafe { mem::uninitialized() },
MaybeUninit을 써보세요.  mem::uninitialized는 deprecate 되었습니다

2020-04-18 18:03 UTC, jeehoonkang commented on src/msqueue.rs
> +            //unimplemented!()
??

2020-04-18 18:03 UTC, jeehoonkang commented on src/msqueue.rs
> +        //unimplemented!()
??

2020-04-18 18:03 UTC, jeehoonkang commented on src/msqueue.rs
> +            //Move tail
"// Move ..." (space)

2020-04-18 18:03 UTC, jeehoonkang commented on src/msqueue.rs
> +            if nextref.is_none() {
`let nextref = some_or!(unsafe { next.as_ref() }, return None);` 가 어떨까 합니다.  아래 보니 unwrap도 하는데 그러지 말고 여기서 unwrap을 하는게 좋겠습니다.

2020-04-18 18:03 UTC, jeehoonkang commented on src/msqueue.rs
> +            let guard = unprotected();
`unprotected()`는 굳이 선언할 필요 없이 필요할때 불러줘도 괜찮을 것 같습ㄴ디ㅏ (123줄에서)

2020-04-18 18:04 UTC, jeehoonkang requested changes

2020-04-18 18:04 UTC, jeehoonkang commented on src/queue.rs
> +//! Segment Queue => skeleton from msqueue + test from segqueue source
아 이게 segment queue군요.  파일 이름을 바꿔주길 바랍니다.

2020-04-18 18:04 UTC, jeehoonkang commented on src/queue.rs
> +//! Segment Queue => skeleton from msqueue + test from segqueue source
ms queue, segment queue의 테스트 코드가 중복인 것 같은데 줄일 수 있을까요?

2020-04-19 15:45 UTC, anemoneflower commented
피드백 해주신부분 수정하였습니다. test들은 test_ftns.rs 파일에 따로 옮겼습니다.

테스트는 잘 되나요?
- 11개 테스트 모두 잘 돌아갑니다.

알고리즘은 이해했는지 궁금합니다.
- 넵.

PR 이름은 좀더 의미가 있어야 합니다. 가령 "Add MSqueue" 정도로..
- 다음 PR부터 반영하도록 하겠습니다. 혹시 지금 merge를 하고 다음 코드리뷰부터 새로 PR을 시작하는 것이 좋을까요?

2020-04-19 23:20 UTC, jeehoonkang requested changes

2020-04-19 23:20 UTC, jeehoonkang commented on src/lib.rs
> +mod test_ftns;
`tests`

2020-04-19 23:20 UTC, jeehoonkang commented on src/test_ftns.rs
> +struct SegQueue<T> {
그냥 segqueue::SegQueue를 바로 사용하면 안되나요?

2020-04-19 23:20 UTC, jeehoonkang commented on src/test_ftns.rs
> +    macro_rules! push_try_pop_1 {
- 이걸 매크로로 하는건 오버킬인 것 같습니다.
- MsQueue와 SegQueue가 모두 구현하는 "Queue" trait을 만들고
- Queue trait에 대해 테스트 함수를 구현한 뒤
- MsQueue, SegQueue에 대해 각각 테스트 함수를 만들어서 위에서 만든 함수를 호출하도록 하는게 어떨까 합니다.

2020-04-19 23:20 UTC, jeehoonkang commented on src/segqueue.rs
> +//! Segment Queue => skeleton from msqueue + test from segqueue source
Segment queue는... 나중에 보겠습니다.

2020-05-10 04:50 UTC, anemoneflower commented on src/test_ftns.rs
> +    macro_rules! push_try_pop_1 {
수정 완료했습니다.

1. scope를 사용하는 테스트 함수는 아래와 같은 에러 메시지가 나와서 각각 따로 구현하였습니다.
`dyn queue::Queue<i64>` cannot be shared between threads safely
the trait `std::marker::Sync` is not implemented for `dyn queue::Queue<queue::LR>`
수정할 방법이 있을까요..?

2. Queue trait에 대한 테스트 함수들을 지금처럼 queue.rs에 두는 것이 좋은지, test.rs 파일을 따로 만드는 것이 좋은지 모르겠습니다.

2020-05-10 11:53 UTC, jeehoonkang requested changes

2020-05-10 11:53 UTC, jeehoonkang commented on src/lib.rs
> +//mod test_ftns;
let's remove it

2020-05-10 11:53 UTC, jeehoonkang commented on src/msqueue.rs
> +        Self: Sized,
`T: Sized`로 대체될 수 있는지 궁금합ㄴ디ㅏ.  `Self`가 등장하는게 다소 의아해서요

2020-05-10 11:53 UTC, jeehoonkang commented on src/msqueue.rs
> +    /// Adds `t` to the back of the queue, possibly waking up threads blocked on `pop`.
"possibly ..."는 아닙니다

2020-05-10 11:53 UTC, jeehoonkang commented on src/msqueue.rs
> +                let _ = self
이 지점에서 tail을 load하는 셈인데, 그 이후에 continue 후에 다시 tail을 load하게 됩니다.  혹시 이걸 한번으로 줄일 수 있을까요?

2020-05-10 11:53 UTC, jeehoonkang commented on src/msqueue.rs
> +                let _ = self
위와 마찬가지 코멘트 들비니다

2020-05-10 11:53 UTC, jeehoonkang commented on src/msqueue.rs
> +            // Move tail
왜 필요한지 주석으로 더 상세히 남겨주세요.

2020-05-10 11:53 UTC, jeehoonkang commented on src/msqueue.rs
> +            match self.try_pop() {
`if let Some(t) = self.try_pop() { ... }`

2020-05-10 11:53 UTC, jeehoonkang commented on src/msqueue.rs
> +    use crate::queue::{
걍 queue::*를 use할 수도 있나요?

2020-05-10 11:53 UTC, jeehoonkang commented on src/test_ftns.rs
> +//! Tests for segqueue and msqueue
이 파일은 queue.rs로 합칩시다

2020-05-11 14:34 UTC, anemoneflower commented on src/msqueue.rs
> +        Self: Sized,
https://doc.rust-lang.org/error-index.html#E0038 에서 "Method references the Self type in its parameters or return type" 의 경우를 참고하였습니다. T: Sized로 수정하면 해당 문제를 수정하지 못하는 듯 합니다.

2020-05-18 05:57 UTC, anemoneflower commented
코드리뷰 수정 완료했습니다.

2020-05-18 06:19 UTC, jeehoonkang requested changes

2020-05-18 06:19 UTC, jeehoonkang commented on src/msqueue.rs
> +        Self: Sized,
저는 여전히 `T: Sized`가 되어야 한다고 생각합니다 이렇게 바꾸면 어떤 에러가 나오는지 알아봐주세요

2020-05-18 06:19 UTC, jeehoonkang commented on src/msqueue.rs
> +            } else {
if 내에서 break 하면, 여기서는 else로 두지 말고 indent를 하나 줄이면 좋겠습니다.

2020-05-18 06:19 UTC, jeehoonkang commented on src/segqueue.rs
> +    pub(crate) data: ManuallyDrop<[UnsafeCell<(T, AtomicBool)>; SEG_SIZE]>,
`data: [UnsafeCell<(MaybeUninit<T>, AtomicBool)>; SEG_SIZE]` 인게 맞을 것 같습니다.  각 T가 uninit일 수도 있으니까요

2020-05-18 06:19 UTC, jeehoonkang commented on src/segqueue.rs
> +        for cell in s.data.iter() {
cargo fmt, cargo clippy 해보시길 바랍니다 아마 `for cell in &s.data {` 라고 추천해줄겁니다

2020-05-18 06:19 UTC, jeehoonkang commented on src/segqueue.rs
> +    pub(crate) data: ManuallyDrop<[UnsafeCell<(T, AtomicBool)>; SEG_SIZE]>,
AtomicBool이 `UnsafeCell`일 필요가 있나요?  `data: [(MaybeUninit<T>, AtomicBool); SEG_SIZE]` 이 맞아보여서요

2020-05-18 06:19 UTC, jeehoonkang commented on src/segqueue.rs
> +            if tail.high.load(Ordering::Relaxed) >= SEG_SIZE {
혹시 high가 SEG_SIZE보다 크면 여기서 next node를 allocate해도 될지 궁금합니다.

2020-05-18 06:19 UTC, jeehoonkang commented on src/segqueue.rs
> +                if low >= cmp::min(head_ref.high.load(Ordering::Relaxed), SEG_SIZE) {
이 로직이 잘 이해되지 않습니다 왜 min?

2020-05-18 06:19 UTC, jeehoonkang commented on src/segqueue.rs
> +                    .compare_and_swap(low, low + 1, Ordering::Relaxed)
`compare_exchange().is_ok()` 로 하는게 어떨까 합니다.

2020-05-18 06:19 UTC, jeehoonkang commented on src/segqueue.rs
> +    //    fn push_try_pop_many_spmc() {
??

2020-05-21 15:12 UTC, anemoneflower commented
push 함수 71번째 줄에서 high가 SEG_SIZE보다 크면 여기서 next node를 allocate해도 될지에 대한 issue(https://github.com/anemoneflower/MSQ_SegQ/pull/2#discussion_r426390823) 를 제외하고 수정 완료했습니다.

2020-05-21 15:25 UTC, anemoneflower commented on src/segqueue.rs
> +            if tail.high.load(Ordering::Relaxed) >= SEG_SIZE {
아래 코드처럼 수정해 보았는데, 잘 되지 않아서 ordering에 대해 고민중입니다..

    fn push(&self, t: T) {
        let guard = &pin();
        loop {
            //load acquire tail
            let mut ta = self.tail.load(Ordering::Acquire, guard);
            let mut tail = unsafe { ta.deref_mut() };
            //check if this is real tail
            if tail.high.load(Ordering::Relaxed) >= SEG_SIZE {
                let new_tail = Owned::new(Segment::new()).into_shared(guard);
                if tail
                    .next
                    .compare_and_set(Shared::null(), new_tail, Ordering::Release, guard)
                    .is_ok()
                {
                    if self
                        .tail
                        .compare_and_set(ta, new_tail, Ordering::Release, guard)
                        .is_ok()
                    {
                        tail = unsafe { self.tail.load(Ordering::Acquire, guard).deref_mut() };
                    } else {
                        continue;
                    }
                } else {
                    continue;
                }
            }

2020-05-21 17:29 UTC, jeehoonkang commented on src/msqueue.rs
> +            //Move tail
이런 사소한건 수정하시고 resolve 눌러주세요.  사소하지 않은건 discussion이 필요할 수 있으므로 남겨두시고..

2020-05-21 17:31 UTC, jeehoonkang commented on src/msqueue.rs
> +            let nextref = some_or!(unsafe { next.as_ref() }, return None);
생각해보니 `let nextref = unsafe { next.as_ref() }?;` 가 더 좋겠습니다.

2020-05-21 17:31 UTC, jeehoonkang commented on src/queue.rs
> +//! Segment Queue => skeleton from msqueue + test from segqueue source
리뷰 반영시 질문에 대해 답변해주시길 부탁드립니다.

2020-05-21 17:32 UTC, jeehoonkang commented on src/msqueue.rs
> +mod test {
`mod tests`가 보다 일반적인 이름인 것 같아요

2020-05-21 17:32 UTC, jeehoonkang commented on src/test_ftns.rs
> +struct SegQueue<T> {
ping

2020-05-21 17:33 UTC, jeehoonkang commented on src/test_ftns.rs
> +    macro_rules! push_try_pop_1 {
`dyn Queue` 말고 `Q: Queue`에 대해 generic하게 test function을 구현하면 어떨까 합니다

2020-05-21 17:33 UTC, jeehoonkang commented on src/segqueue.rs
> +//! Segment Queue => skeleton from msqueue + test from segqueue source
그러고보니 "segmented queue"인 것 같아요

2020-05-21 17:34 UTC, jeehoonkang commented on src/msqueue.rs
> +                let _ = self
ping

2020-05-21 17:34 UTC, jeehoonkang commented on src/msqueue.rs
> +            // Move tail
ping

2020-05-21 17:34 UTC, jeehoonkang commented on src/msqueue.rs
> +            } else {
일단 conversation들을 모두 확인하고 사소한건 resolve해주세요.  그 이후에 다시 리뷰하겠습니다.

2020-05-21 17:35 UTC, jeehoonkang requested changes
.

2020-05-25 06:09 UTC, anemoneflower commented on src/segqueue.rs
> +                if low >= cmp::min(head_ref.high.load(Ordering::Relaxed), SEG_SIZE) {
주석에 추가해 두었습니다.
Need to use 'min' because, high might be bigger than SEG_SIZE if there is case like cur_high >= SEG_SIZE in push() function(line 91).

2020-05-26 15:11 UTC, anemoneflower commented on src/segqueue.rs
> +            if tail.high.load(Ordering::Relaxed) >= SEG_SIZE {
A: 원래 코드대로 push완료 후, tail.high를 체크하고 next node를 allocate 하는 경우 다른 thread가 push를 하려고 해도 `if tail.high.load(Ordering::Relaxed) >= SEG_SIZE`(72줄)에서 `continue` 를 하기 때문에 새 노드가 allocate될 때 까지 loop를 돌아야 합니다.

B: 그런데, `if tail.high.load(Ordering::Relaxed) >= SEG_SIZE` 에서 새 노드를 allocate하려고 하면, 여러 thread들이 동시에 next node의 allocate를 시도할 수 있습니다. 다른 thread의 동작에 영향을 줄 수 있는 allocate과정은 다음과 같다고 생각했습니다.

1. tail.next에 new_tail setting
2. self.tail에 new_tail setting

두 단계 모두 위 코드(https://github.com/anemoneflower/MSQ_SegQ/pull/2#discussion_r428726442 )와 같이 CAS로 이루어지면 A처럼 동작할 것이라고 생각했는데, 구현해보니 어딘가 빠트린 부분이 있는 것 같습니다.

1과 2에서 CAS를 하는 것 말고 또 고려해야 할 부분이 무엇일까요?

2020-05-28 01:19 UTC, jeehoonkang requested changes

2020-05-28 01:19 UTC, jeehoonkang commented on src/segqueue.rs
> +            unsafe {
`unsafe` 사용을 최대한 줄여보세요.  가령 `if cur_high >= ...` 부분은 밖으로 빼도 됩니다.

2020-05-28 01:19 UTC, jeehoonkang commented on src/segqueue.rs
> +                    // Need to use 'min' because, high might be bigger than SEG_SIZE if there is case like cur_high >= SEG_SIZE in push() function(line 91).
이 주석은 if 위에 달려야 합니다.  보다 일반적으로 왜 이런 상황에서 break하는지 남겨주세요.

2020-05-28 01:19 UTC, jeehoonkang commented on src/segqueue.rs
> +                    // Need to use 'min' because, high might be bigger than SEG_SIZE if there is case like cur_high >= SEG_SIZE in push() function(line 91).
cargo fmt 해서 line break 넣어주세요.

2020-05-28 01:19 UTC, jeehoonkang commented on src/segqueue.rs
> +                    // Need to use 'min' because, high might be bigger than SEG_SIZE if there is case like cur_high >= SEG_SIZE in push() function(line 91).
여전히 이해가 잘 안되긴 합니다.  고치신 후에 다시 보겠습니다.

2020-05-28 01:19 UTC, jeehoonkang commented on src/segqueue.rs
> +            if tail.high.load(Ordering::Relaxed) >= SEG_SIZE {
일단 이 제안은 철회하는 걸로 하겠습니다.  원래대로 돌아가서 해봅시다..

2020-05-28 01:19 UTC, jeehoonkang commented on src/segqueue.rs
> +                    loop {
`while !(*cell).1.load(Ordering::Acquire) {}` 로 바꿀 수 있습니다.

2020-05-28 01:19 UTC, jeehoonkang commented on src/segqueue.rs
> +                    return unsafe { Some(ptr::read((*cell).0.as_ptr())) };
- early return principle에 따라, `if low + 1 != SEG_SIZE { return ... }` 꼴로 바꿔주세요.
- 일반적으로 모든 곳에서 control flow를 최대한 단순하게 만들어주세요

2020-05-28 01:19 UTC, jeehoonkang commented on src/segqueue.rs
> +        if h.low.load(Ordering::Relaxed) >= cmp::min(h.high.load(Ordering::Relaxed), SEG_SIZE) {
if ... { return false; } 로 작성하는게 readability가 올라갈 것 같아요.

2020-05-29 07:14 UTC, merged

2020-05-30 06:45 UTC, anemoneflower commented on src/segqueue.rs
> +                    // Need to use 'min' because, high might be bigger than SEG_SIZE if there is case like cur_high >= SEG_SIZE in push() function(line 91).
다시 생각해 보니 min이 필요 없는게 맞는 것 같습니다.
주석 수정해서 새 PR 올리겠습니다.