Add MSQueue, SegQueue, Queue Test
anemoneflower/MSQ_SegQ pull request #4
Opened 2020-05-30 06:53 UTC by anemoneflower

이전 코드리뷰 수정하였습니다.

- trait 주석
- unsafe 사용 줄이기

2020-05-30 06:55 UTC, anemoneflower commented on src/segqueue.rs
> +                // If head is empty, load head again.
주석 수정

2020-05-30 06:56 UTC, anemoneflower commented on src/segqueue.rs
> +                    while !(*cell).1.load(Ordering::Acquire) {}
while문으로 수정

2020-05-30 06:56 UTC, anemoneflower commented on src/segqueue.rs
> +                    if low + 1 != SEG_SIZE {
early return principle에 따라 수정

2020-05-30 06:57 UTC, anemoneflower commented on src/segqueue.rs
> +        if h.low.load(Ordering::Relaxed) < cmp::min(h.high.load(Ordering::Relaxed), SEG_SIZE) {
readability 관련 부분 수정

2020-06-01 10:12 UTC, jeehoonkang requested changes

2020-06-01 10:12 UTC, jeehoonkang commented on .gitignore
> +# User-specific stuff
그냥 `/.idea` 전체를 ignore해도 되나요?

2020-06-01 10:12 UTC, jeehoonkang commented on .gitignore
> +.idea/caches/build_file_checksums.ser
newline

2020-06-01 10:12 UTC, jeehoonkang commented on .idea/lockfree.iml
> +      <sourceFolder url="file://D:/lockfree\examples" isTestSource="false" />
`D:`가 repo에 들어가는게 좀 어색합니다.

2020-06-01 10:12 UTC, jeehoonkang commented on .idea/lockfree.iml
> +      <sourceFolder url="file://D:/lockfree\examples" isTestSource="false" />
.idea 전부 ignore하는게 좋겠어요

2020-06-01 10:12 UTC, jeehoonkang commented on src/queue_test.rs
> +    let q = qq.deref();
이게 왜 필요한지 궁금합니다.

2020-06-01 17:08 UTC, closed without merging